name: Create release of shiori

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            os: ubuntu-latest,
            artifact_name: shiori,
            asset_name: shiori-linux-amd64,
            strip: true
            }
          - {
            os: windows-latest,
            artifact_name: shiori.exe,
            asset_name: shiori-windows-amd64,
            strip: false
            }
          - {
            os: macos-latest,
            artifact_name: shiori,
            asset_name: shiori-macos-amd64,
            strip: true
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Build
        run: go mod download && go build
      - name: Install macOS dependencies
        if: matrix.config.os == 'macos-latest'
        run: brew install p7zip
      - name: Zip binary file
        run: 7z a ./${{ matrix.config.asset_name }}.zip ./${{ matrix.config.artifact_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ./${{ matrix.config.asset_name }}.zip
          asset_name: ${{ matrix.config.asset_name }}.zip
          tag: ${{ github.ref }}
